name: Release

permissions:
  contents: write

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: armv7-unknown-linux-musleabihf
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: run cross-build
        uses: ahaoboy/cross-build@v1
        with:
          bin: ejs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.target }}
          RUSTFLAGS: ${{ matrix.RUSTFLAGS }}
          tag: nightly
          allowUpdates: true
          no-default-features: true
          features: external,qjs,bindgen
